name: randomness
description: Random number generator (RNG) with options for adding weights
version: 0.2.1
repository: https://github.com/MadSimple/randomness

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.26.0
